### ISSUE TITLE
Error in NonGUIDriver

### ISSUE THREAD

**Issue by eostermueller** [eostermueller/performanceGolf#1]
Shawn M. reported the following problem when running PS_HOME/db/loadDb.sh.
I have made a change to the two .jmx files in PS_HOME/db.
Those .jmx files were unnecessarily referencing 3rd part dependency (JMeterPlugins).
I've removed the references and retested locally.
--Erik
```
Got as far as running the loadDb script.  Getting this error:
Error in NonGUIDriver java.lang.NullPointerException
2016/06/10 08:32:01 ERROR - jmeter.JMeter: Error in NonGUIDriver java.lang.NullPointerException
        at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:92)
        at org.apache.jmeter.JMeter.runNonGui(JMeter.java:754)
        at org.apache.jmeter.JMeter.startNonGui(JMeter.java:732)
        at org.apache.jmeter.JMeter.start(JMeter.java:390)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.jmeter.NewDriver.main(NewDriver.java:259)

smckinn@ubuntu:~/tmp/Erik/1/perfSandbox/
```

**Comment by eostermueller** [comment]
Here are links to the two files that required fixes for this issue:
https://github.com/eostermueller/perfSandbox/blob/master/db/loadDb-01.jmx
https://github.com/eostermueller/perfSandbox/blob/master/db/loadDb-02.jmx
